# Generated by Django 4.2.7 on 2024-02-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
