# Generated by Django 4.2.7 on 2024-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_term_task_datetime_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_joined',
            field=models.DateField(auto_now=True, verbose_name='Дата и время добавления'),
        ),
    ]
