# Generated by Django 4.2.7 on 2024-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_datetime_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_joined',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время добавления'),
        ),
    ]
