# Generated by Django 4.2.7 on 2024-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_datetime_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления'),
        ),
    ]
